version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: taracol_dev
      POSTGRES_USER: taracol
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  gateway:
    build:
      context: .
      dockerfile: infrastructure/docker/gateway.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - identity-service
      - web-service

  identity-service:
    build:
      context: .
      dockerfile: infrastructure/docker/identity-service.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://taracol:development@postgres/taracol_dev
      REDIS_URL: redis://redis

  web-service:
    build:
      context: .
      dockerfile: infrastructure/docker/web-service.Dockerfile  
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://taracol:development@postgres/taracol_dev
      REDIS_URL: redis://redis

volumes:
  postgres_data:
